onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate /testbench/clk
add wave -noupdate /testbench/clk
add wave -noupdate -radix hexadecimal -childformat {{{/testbench/processor/c/cpu_d/id_stage/reg_file/data[7]} -radix hexadecimal} {{/testbench/processor/c/cpu_d/id_stage/reg_file/data[6]} -radix hexadecimal} {{/testbench/processor/c/cpu_d/id_stage/reg_file/data[5]} -radix hexadecimal} {{/testbench/processor/c/cpu_d/id_stage/reg_file/data[4]} -radix hexadecimal} {{/testbench/processor/c/cpu_d/id_stage/reg_file/data[3]} -radix hexadecimal} {{/testbench/processor/c/cpu_d/id_stage/reg_file/data[2]} -radix hexadecimal} {{/testbench/processor/c/cpu_d/id_stage/reg_file/data[1]} -radix hexadecimal} {{/testbench/processor/c/cpu_d/id_stage/reg_file/data[0]} -radix hexadecimal}} -expand -subitemconfig {{/testbench/processor/c/cpu_d/id_stage/reg_file/data[7]} {-height 16 -radix hexadecimal} {/testbench/processor/c/cpu_d/id_stage/reg_file/data[6]} {-height 16 -radix hexadecimal} {/testbench/processor/c/cpu_d/id_stage/reg_file/data[5]} {-height 16 -radix hexadecimal} {/testbench/processor/c/cpu_d/id_stage/reg_file/data[4]} {-height 16 -radix hexadecimal} {/testbench/processor/c/cpu_d/id_stage/reg_file/data[3]} {-height 16 -radix hexadecimal} {/testbench/processor/c/cpu_d/id_stage/reg_file/data[2]} {-height 16 -radix hexadecimal} {/testbench/processor/c/cpu_d/id_stage/reg_file/data[1]} {-height 16 -radix hexadecimal} {/testbench/processor/c/cpu_d/id_stage/reg_file/data[0]} {-height 16 -radix hexadecimal}} /testbench/processor/c/cpu_d/id_stage/reg_file/data
add wave -noupdate -color Gold -radix hexadecimal /testbench/processor/pmem_wb/ADR
add wave -noupdate -color Gold -radix hexadecimal /testbench/processor/pmem_wb/WE
add wave -noupdate -color Gold -radix hexadecimal /testbench/processor/pmem_wb/CYC
add wave -noupdate -color Gold -radix hexadecimal /testbench/processor/pmem_wb/SEL
add wave -noupdate -color Gold -radix hexadecimal /testbench/processor/pmem_wb/ACK
add wave -noupdate -radix hexadecimal /testbench/processor/l2_interconnect/ADR
add wave -noupdate -radix hexadecimal /testbench/processor/l2_interconnect/WE
add wave -noupdate -radix hexadecimal /testbench/processor/l2_interconnect/SEL
add wave -noupdate -radix hexadecimal /testbench/processor/l2_interconnect/CYC
add wave -noupdate -radix hexadecimal /testbench/processor/l2_interconnect/ACK
add wave -noupdate -color Cyan -radix hexadecimal /testbench/processor/dmem_interconnect/ADR
add wave -noupdate -color Cyan -radix hexadecimal /testbench/processor/dmem_interconnect/WE
add wave -noupdate -color Cyan -radix hexadecimal /testbench/processor/dmem_interconnect/SEL
add wave -noupdate -color Cyan -radix hexadecimal /testbench/processor/dmem_interconnect/CYC
add wave -noupdate -color Cyan -radix hexadecimal /testbench/processor/dmem_interconnect/ACK
add wave -noupdate /testbench/clk
add wave -noupdate -radix hexadecimal -childformat {{{/testbench/processor/c/cpu_d/id_stage/reg_file/data[7]} -radix hexadecimal} {{/testbench/processor/c/cpu_d/id_stage/reg_file/data[6]} -radix hexadecimal} {{/testbench/processor/c/cpu_d/id_stage/reg_file/data[5]} -radix hexadecimal} {{/testbench/processor/c/cpu_d/id_stage/reg_file/data[4]} -radix hexadecimal} {{/testbench/processor/c/cpu_d/id_stage/reg_file/data[3]} -radix hexadecimal} {{/testbench/processor/c/cpu_d/id_stage/reg_file/data[2]} -radix hexadecimal} {{/testbench/processor/c/cpu_d/id_stage/reg_file/data[1]} -radix hexadecimal} {{/testbench/processor/c/cpu_d/id_stage/reg_file/data[0]} -radix hexadecimal}} -expand -subitemconfig {{/testbench/processor/c/cpu_d/id_stage/reg_file/data[7]} {-height 16 -radix hexadecimal} {/testbench/processor/c/cpu_d/id_stage/reg_file/data[6]} {-height 16 -radix hexadecimal} {/testbench/processor/c/cpu_d/id_stage/reg_file/data[5]} {-height 16 -radix hexadecimal} {/testbench/processor/c/cpu_d/id_stage/reg_file/data[4]} {-height 16 -radix hexadecimal} {/testbench/processor/c/cpu_d/id_stage/reg_file/data[3]} {-height 16 -radix hexadecimal} {/testbench/processor/c/cpu_d/id_stage/reg_file/data[2]} {-height 16 -radix hexadecimal} {/testbench/processor/c/cpu_d/id_stage/reg_file/data[1]} {-height 16 -radix hexadecimal} {/testbench/processor/c/cpu_d/id_stage/reg_file/data[0]} {-height 16 -radix hexadecimal}} /testbench/processor/c/cpu_d/id_stage/reg_file/data
add wave -noupdate -radix hexadecimal /testbench/processor/c/cpu_d/mem_stage/m_stall/mem_addr_mux/sel
add wave -noupdate -radix hexadecimal /testbench/processor/c/cpu_d/mem_stage/m_stall/mem_addr_mux/a
add wave -noupdate -radix hexadecimal /testbench/processor/c/cpu_d/mem_stage/m_stall/mem_addr_mux/b
add wave -noupdate -radix hexadecimal /testbench/processor/c/cpu_d/mem_stage/m_stall/mem_addr_mux/f
add wave -noupdate -radix hexadecimal /testbench/processor/c/cpu_d/dmem_address
add wave -noupdate -radix hexadecimal /testbench/processor/c/cpu_d/mem_stage/dmem_address
add wave -noupdate -radix hexadecimal /testbench/processor/dmem_wb/ADR
add wave -noupdate -radix hexadecimal /testbench/processor/l1_dcache/mem_address
add wave -noupdate -radix hexadecimal /testbench/processor/l1_dcache/pmem_address
add wave -noupdate -radix hexadecimal -childformat {{{/testbench/processor/l1_dcache/cache_d/dirty0/data[15]} -radix hexadecimal} {{/testbench/processor/l1_dcache/cache_d/dirty0/data[14]} -radix hexadecimal} {{/testbench/processor/l1_dcache/cache_d/dirty0/data[13]} -radix hexadecimal} {{/testbench/processor/l1_dcache/cache_d/dirty0/data[12]} -radix hexadecimal} {{/testbench/processor/l1_dcache/cache_d/dirty0/data[11]} -radix hexadecimal} {{/testbench/processor/l1_dcache/cache_d/dirty0/data[10]} -radix hexadecimal} {{/testbench/processor/l1_dcache/cache_d/dirty0/data[9]} -radix hexadecimal} {{/testbench/processor/l1_dcache/cache_d/dirty0/data[8]} -radix hexadecimal} {{/testbench/processor/l1_dcache/cache_d/dirty0/data[7]} -radix hexadecimal} {{/testbench/processor/l1_dcache/cache_d/dirty0/data[6]} -radix hexadecimal} {{/testbench/processor/l1_dcache/cache_d/dirty0/data[5]} -radix hexadecimal} {{/testbench/processor/l1_dcache/cache_d/dirty0/data[4]} -radix hexadecimal} {{/testbench/processor/l1_dcache/cache_d/dirty0/data[3]} -radix hexadecimal} {{/testbench/processor/l1_dcache/cache_d/dirty0/data[2]} -radix hexadecimal} {{/testbench/processor/l1_dcache/cache_d/dirty0/data[1]} -radix hexadecimal} {{/testbench/processor/l1_dcache/cache_d/dirty0/data[0]} -radix hexadecimal}} -subitemconfig {{/testbench/processor/l1_dcache/cache_d/dirty0/data[15]} {-height 16 -radix hexadecimal} {/testbench/processor/l1_dcache/cache_d/dirty0/data[14]} {-height 16 -radix hexadecimal} {/testbench/processor/l1_dcache/cache_d/dirty0/data[13]} {-height 16 -radix hexadecimal} {/testbench/processor/l1_dcache/cache_d/dirty0/data[12]} {-height 16 -radix hexadecimal} {/testbench/processor/l1_dcache/cache_d/dirty0/data[11]} {-height 16 -radix hexadecimal} {/testbench/processor/l1_dcache/cache_d/dirty0/data[10]} {-height 16 -radix hexadecimal} {/testbench/processor/l1_dcache/cache_d/dirty0/data[9]} {-height 16 -radix hexadecimal} {/testbench/processor/l1_dcache/cache_d/dirty0/data[8]} {-height 16 -radix hexadecimal} {/testbench/processor/l1_dcache/cache_d/dirty0/data[7]} {-height 16 -radix hexadecimal} {/testbench/processor/l1_dcache/cache_d/dirty0/data[6]} {-height 16 -radix hexadecimal} {/testbench/processor/l1_dcache/cache_d/dirty0/data[5]} {-height 16 -radix hexadecimal} {/testbench/processor/l1_dcache/cache_d/dirty0/data[4]} {-height 16 -radix hexadecimal} {/testbench/processor/l1_dcache/cache_d/dirty0/data[3]} {-height 16 -radix hexadecimal} {/testbench/processor/l1_dcache/cache_d/dirty0/data[2]} {-height 16 -radix hexadecimal} {/testbench/processor/l1_dcache/cache_d/dirty0/data[1]} {-height 16 -radix hexadecimal} {/testbench/processor/l1_dcache/cache_d/dirty0/data[0]} {-height 16 -radix hexadecimal}} /testbench/processor/l1_dcache/cache_d/dirty0/data
add wave -noupdate -radix hexadecimal -childformat {{{/testbench/processor/l1_dcache/cache_d/dirty1/data[15]} -radix hexadecimal} {{/testbench/processor/l1_dcache/cache_d/dirty1/data[14]} -radix hexadecimal} {{/testbench/processor/l1_dcache/cache_d/dirty1/data[13]} -radix hexadecimal} {{/testbench/processor/l1_dcache/cache_d/dirty1/data[12]} -radix hexadecimal} {{/testbench/processor/l1_dcache/cache_d/dirty1/data[11]} -radix hexadecimal} {{/testbench/processor/l1_dcache/cache_d/dirty1/data[10]} -radix hexadecimal} {{/testbench/processor/l1_dcache/cache_d/dirty1/data[9]} -radix hexadecimal} {{/testbench/processor/l1_dcache/cache_d/dirty1/data[8]} -radix hexadecimal} {{/testbench/processor/l1_dcache/cache_d/dirty1/data[7]} -radix hexadecimal} {{/testbench/processor/l1_dcache/cache_d/dirty1/data[6]} -radix hexadecimal} {{/testbench/processor/l1_dcache/cache_d/dirty1/data[5]} -radix hexadecimal} {{/testbench/processor/l1_dcache/cache_d/dirty1/data[4]} -radix hexadecimal} {{/testbench/processor/l1_dcache/cache_d/dirty1/data[3]} -radix hexadecimal} {{/testbench/processor/l1_dcache/cache_d/dirty1/data[2]} -radix hexadecimal} {{/testbench/processor/l1_dcache/cache_d/dirty1/data[1]} -radix hexadecimal} {{/testbench/processor/l1_dcache/cache_d/dirty1/data[0]} -radix hexadecimal}} -subitemconfig {{/testbench/processor/l1_dcache/cache_d/dirty1/data[15]} {-height 16 -radix hexadecimal} {/testbench/processor/l1_dcache/cache_d/dirty1/data[14]} {-height 16 -radix hexadecimal} {/testbench/processor/l1_dcache/cache_d/dirty1/data[13]} {-height 16 -radix hexadecimal} {/testbench/processor/l1_dcache/cache_d/dirty1/data[12]} {-height 16 -radix hexadecimal} {/testbench/processor/l1_dcache/cache_d/dirty1/data[11]} {-height 16 -radix hexadecimal} {/testbench/processor/l1_dcache/cache_d/dirty1/data[10]} {-height 16 -radix hexadecimal} {/testbench/processor/l1_dcache/cache_d/dirty1/data[9]} {-height 16 -radix hexadecimal} {/testbench/processor/l1_dcache/cache_d/dirty1/data[8]} {-height 16 -radix hexadecimal} {/testbench/processor/l1_dcache/cache_d/dirty1/data[7]} {-height 16 -radix hexadecimal} {/testbench/processor/l1_dcache/cache_d/dirty1/data[6]} {-height 16 -radix hexadecimal} {/testbench/processor/l1_dcache/cache_d/dirty1/data[5]} {-height 16 -radix hexadecimal} {/testbench/processor/l1_dcache/cache_d/dirty1/data[4]} {-height 16 -radix hexadecimal} {/testbench/processor/l1_dcache/cache_d/dirty1/data[3]} {-height 16 -radix hexadecimal} {/testbench/processor/l1_dcache/cache_d/dirty1/data[2]} {-height 16 -radix hexadecimal} {/testbench/processor/l1_dcache/cache_d/dirty1/data[1]} {-height 16 -radix hexadecimal} {/testbench/processor/l1_dcache/cache_d/dirty1/data[0]} {-height 16 -radix hexadecimal}} /testbench/processor/l1_dcache/cache_d/dirty1/data
add wave -noupdate -radix hexadecimal -childformat {{{/testbench/processor/l1_dcache/cache_d/tag0/data[15]} -radix hexadecimal} {{/testbench/processor/l1_dcache/cache_d/tag0/data[14]} -radix hexadecimal} {{/testbench/processor/l1_dcache/cache_d/tag0/data[13]} -radix hexadecimal} {{/testbench/processor/l1_dcache/cache_d/tag0/data[12]} -radix hexadecimal} {{/testbench/processor/l1_dcache/cache_d/tag0/data[11]} -radix hexadecimal} {{/testbench/processor/l1_dcache/cache_d/tag0/data[10]} -radix hexadecimal} {{/testbench/processor/l1_dcache/cache_d/tag0/data[9]} -radix hexadecimal} {{/testbench/processor/l1_dcache/cache_d/tag0/data[8]} -radix hexadecimal} {{/testbench/processor/l1_dcache/cache_d/tag0/data[7]} -radix hexadecimal} {{/testbench/processor/l1_dcache/cache_d/tag0/data[6]} -radix hexadecimal} {{/testbench/processor/l1_dcache/cache_d/tag0/data[5]} -radix hexadecimal} {{/testbench/processor/l1_dcache/cache_d/tag0/data[4]} -radix hexadecimal} {{/testbench/processor/l1_dcache/cache_d/tag0/data[3]} -radix hexadecimal} {{/testbench/processor/l1_dcache/cache_d/tag0/data[2]} -radix hexadecimal} {{/testbench/processor/l1_dcache/cache_d/tag0/data[1]} -radix hexadecimal} {{/testbench/processor/l1_dcache/cache_d/tag0/data[0]} -radix hexadecimal}} -subitemconfig {{/testbench/processor/l1_dcache/cache_d/tag0/data[15]} {-height 16 -radix hexadecimal} {/testbench/processor/l1_dcache/cache_d/tag0/data[14]} {-height 16 -radix hexadecimal} {/testbench/processor/l1_dcache/cache_d/tag0/data[13]} {-height 16 -radix hexadecimal} {/testbench/processor/l1_dcache/cache_d/tag0/data[12]} {-height 16 -radix hexadecimal} {/testbench/processor/l1_dcache/cache_d/tag0/data[11]} {-height 16 -radix hexadecimal} {/testbench/processor/l1_dcache/cache_d/tag0/data[10]} {-height 16 -radix hexadecimal} {/testbench/processor/l1_dcache/cache_d/tag0/data[9]} {-height 16 -radix hexadecimal} {/testbench/processor/l1_dcache/cache_d/tag0/data[8]} {-height 16 -radix hexadecimal} {/testbench/processor/l1_dcache/cache_d/tag0/data[7]} {-height 16 -radix hexadecimal} {/testbench/processor/l1_dcache/cache_d/tag0/data[6]} {-height 16 -radix hexadecimal} {/testbench/processor/l1_dcache/cache_d/tag0/data[5]} {-height 16 -radix hexadecimal} {/testbench/processor/l1_dcache/cache_d/tag0/data[4]} {-height 16 -radix hexadecimal} {/testbench/processor/l1_dcache/cache_d/tag0/data[3]} {-height 16 -radix hexadecimal} {/testbench/processor/l1_dcache/cache_d/tag0/data[2]} {-height 16 -radix hexadecimal} {/testbench/processor/l1_dcache/cache_d/tag0/data[1]} {-height 16 -radix hexadecimal} {/testbench/processor/l1_dcache/cache_d/tag0/data[0]} {-height 16 -radix hexadecimal}} /testbench/processor/l1_dcache/cache_d/tag0/data
add wave -noupdate -radix hexadecimal -childformat {{{/testbench/processor/l1_dcache/cache_d/tag1/data[15]} -radix hexadecimal} {{/testbench/processor/l1_dcache/cache_d/tag1/data[14]} -radix hexadecimal} {{/testbench/processor/l1_dcache/cache_d/tag1/data[13]} -radix hexadecimal} {{/testbench/processor/l1_dcache/cache_d/tag1/data[12]} -radix hexadecimal} {{/testbench/processor/l1_dcache/cache_d/tag1/data[11]} -radix hexadecimal} {{/testbench/processor/l1_dcache/cache_d/tag1/data[10]} -radix hexadecimal} {{/testbench/processor/l1_dcache/cache_d/tag1/data[9]} -radix hexadecimal} {{/testbench/processor/l1_dcache/cache_d/tag1/data[8]} -radix hexadecimal} {{/testbench/processor/l1_dcache/cache_d/tag1/data[7]} -radix hexadecimal} {{/testbench/processor/l1_dcache/cache_d/tag1/data[6]} -radix hexadecimal} {{/testbench/processor/l1_dcache/cache_d/tag1/data[5]} -radix hexadecimal} {{/testbench/processor/l1_dcache/cache_d/tag1/data[4]} -radix hexadecimal} {{/testbench/processor/l1_dcache/cache_d/tag1/data[3]} -radix hexadecimal} {{/testbench/processor/l1_dcache/cache_d/tag1/data[2]} -radix hexadecimal} {{/testbench/processor/l1_dcache/cache_d/tag1/data[1]} -radix hexadecimal} {{/testbench/processor/l1_dcache/cache_d/tag1/data[0]} -radix hexadecimal}} -subitemconfig {{/testbench/processor/l1_dcache/cache_d/tag1/data[15]} {-height 16 -radix hexadecimal} {/testbench/processor/l1_dcache/cache_d/tag1/data[14]} {-height 16 -radix hexadecimal} {/testbench/processor/l1_dcache/cache_d/tag1/data[13]} {-height 16 -radix hexadecimal} {/testbench/processor/l1_dcache/cache_d/tag1/data[12]} {-height 16 -radix hexadecimal} {/testbench/processor/l1_dcache/cache_d/tag1/data[11]} {-height 16 -radix hexadecimal} {/testbench/processor/l1_dcache/cache_d/tag1/data[10]} {-height 16 -radix hexadecimal} {/testbench/processor/l1_dcache/cache_d/tag1/data[9]} {-height 16 -radix hexadecimal} {/testbench/processor/l1_dcache/cache_d/tag1/data[8]} {-height 16 -radix hexadecimal} {/testbench/processor/l1_dcache/cache_d/tag1/data[7]} {-height 16 -radix hexadecimal} {/testbench/processor/l1_dcache/cache_d/tag1/data[6]} {-height 16 -radix hexadecimal} {/testbench/processor/l1_dcache/cache_d/tag1/data[5]} {-height 16 -radix hexadecimal} {/testbench/processor/l1_dcache/cache_d/tag1/data[4]} {-height 16 -radix hexadecimal} {/testbench/processor/l1_dcache/cache_d/tag1/data[3]} {-height 16 -radix hexadecimal} {/testbench/processor/l1_dcache/cache_d/tag1/data[2]} {-height 16 -radix hexadecimal} {/testbench/processor/l1_dcache/cache_d/tag1/data[1]} {-height 16 -radix hexadecimal} {/testbench/processor/l1_dcache/cache_d/tag1/data[0]} {-height 16 -radix hexadecimal}} /testbench/processor/l1_dcache/cache_d/tag1/data
add wave -noupdate -radix hexadecimal /testbench/processor/l1_dcache/cache_d/tag
add wave -noupdate -radix hexadecimal -childformat {{{/testbench/processor/l1_dcache/cache_d/index[3]} -radix hexadecimal} {{/testbench/processor/l1_dcache/cache_d/index[2]} -radix hexadecimal} {{/testbench/processor/l1_dcache/cache_d/index[1]} -radix hexadecimal} {{/testbench/processor/l1_dcache/cache_d/index[0]} -radix hexadecimal}} -expand -subitemconfig {{/testbench/processor/l1_dcache/cache_d/index[3]} {-radix hexadecimal} {/testbench/processor/l1_dcache/cache_d/index[2]} {-radix hexadecimal} {/testbench/processor/l1_dcache/cache_d/index[1]} {-radix hexadecimal} {/testbench/processor/l1_dcache/cache_d/index[0]} {-radix hexadecimal}} /testbench/processor/l1_dcache/cache_d/index
add wave -noupdate /testbench/processor/l1_dcache/cache_d/lru_out
add wave -noupdate -radix hexadecimal /testbench/processor/l1_dcache/cache_d/tag_out
add wave -noupdate -radix hexadecimal /testbench/processor/l1_dcache/cache_d/write_back_addr
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {32530729 ps} 0}
quietly wave cursor active 1
configure wave -namecolwidth 437
configure wave -valuecolwidth 75
configure wave -justifyvalue left
configure wave -signalnamewidth 0
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ns
update
WaveRestoreZoom {32213930 ps} {32915221 ps}
